const fs = require('fs');

const indexHtml = fs.readFileSync('index.html', 'utf8');

// We need to build franchise.html.
// Let's use a simpler approach: copy the entire index.html, then gut the middle sections.
// Sections to remove:
// <section id="block2"> ...
// <section id="block3"> ...
// <section id="b4-header"> ...
// <section id="block4"> ...
// <section id="block5"> ...
// <section id="book"> ...
// <section id="franchise"> ...
// <section id="journal"> ...
// <section id="contact"> ...
// Plus whatever the hero content is, except the header.
